// <auto-generated />
using System;
using Fiap.Banco.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Banco.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506012024_CriacaoInicialPrefixada")]
    partial class CriacaoInicialPrefixada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Banco.API.Models.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("NUMERO");

                    b.HasKey("Id")
                        .HasName("PK_PB_AGENCIAS");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("IX_PB_AGENCIAS_NUMERO");

                    b.ToTable("PB_AGENCIAS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Endereco = "Avenida Paulista, São Paulo",
                            Nome = "Agência Paulista",
                            Numero = "0001"
                        });
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenciaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AGENCIAID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("TIPOCLIENTE");

                    b.HasKey("Id")
                        .HasName("PK_PB_CLIENTES");

                    b.HasIndex("AgenciaId")
                        .HasDatabaseName("IX_PB_CLIENTES_AGENCIAID");

                    b.ToTable("PB_CLIENTES");

                    b.HasDiscriminator<string>("TipoCliente").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Contratacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLIENTEID");

                    b.Property<string>("CnpjEmpresaEmpregadora")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CNPJEMPRESAEMPREGADORA");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATASOLICITACAO");

                    b.Property<string>("MotivoReprovacao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MOTIVOREPROVACAO");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUTOID");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id")
                        .HasName("PK_PB_CONTRATACOES");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_PB_CONTRATACOES_CLIENTEID");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("IX_PB_CONTRATACOES_PRODUTOID");

                    b.ToTable("PB_CONTRATACOES");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.EmpresaConveniada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ativa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ATIVA");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RAZAOSOCIAL");

                    b.HasKey("Id")
                        .HasName("PK_PB_EMPRESASCONVENIADAS");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("IX_PB_EMPRESASCONVENIADAS_CNPJ");

                    b.ToTable("PB_EMPRESASCONVENIADAS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = 1,
                            Cnpj = "12345678000199",
                            RazaoSocial = "Empresa Conveniada FIAP LTDA"
                        });
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)")
                        .HasColumnName("TIPOPRODUTO");

                    b.HasKey("Id")
                        .HasName("PK_PB_PRODUTOS");

                    b.ToTable("PB_PRODUTOS");

                    b.HasDiscriminator<string>("TipoProduto").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.PessoaFisica", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Cliente");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATANASCIMENTO");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_PB_CLIENTES_CPF")
                        .HasFilter("\"CPF\" IS NOT NULL");

                    b.ToTable("PB_CLIENTES");

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.PessoaJuridica", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Cliente");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RAZAOSOCIAL");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("IX_PB_CLIENTES_CNPJ")
                        .HasFilter("\"CNPJ\" IS NOT NULL");

                    b.ToTable("PB_CLIENTES");

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Emprestimo", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Produto");

                    b.Property<decimal>("TaxaJurosMensal")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TAXAJUROSMENSAL");

                    b.ToTable("PB_PRODUTOS");

                    b.HasDiscriminator().HasValue("EMPRESTIMO");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.MaquinaDeCartao", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Produto");

                    b.Property<decimal>("TaxaMdr")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TAXAMDR");

                    b.ToTable("PB_PRODUTOS");

                    b.HasDiscriminator().HasValue("MAQUINA_CARTAO");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.ReceberSalario", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Produto");

                    b.Property<int>("ExigeConvenioEmpresa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EXIGECONVENIOEMPRESA");

                    b.ToTable("PB_PRODUTOS");

                    b.HasDiscriminator().HasValue("RECEBER_SALARIO");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Receber Salário",
                            ExigeConvenioEmpresa = 1
                        });
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Cliente", b =>
                {
                    b.HasOne("Fiap.Banco.API.Models.Agencia", "Agencia")
                        .WithMany("Clientes")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PB_CLIENTES_PB_AGENCIAS");

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Contratacao", b =>
                {
                    b.HasOne("Fiap.Banco.API.Models.Cliente", "Cliente")
                        .WithMany("Contratacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PB_CONTRATACOES_PB_CLIENTES");

                    b.HasOne("Fiap.Banco.API.Models.Produto", "Produto")
                        .WithMany("Contratacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PB_CONTRATACOES_Produtos");

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Agencia", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Cliente", b =>
                {
                    b.Navigation("Contratacoes");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Produto", b =>
                {
                    b.Navigation("Contratacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
